# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets

from desktop_notifier import DesktopNotifier

import sqlite3
try:
    conn = sqlite3.connect('stock.db')
    c = conn.cursor()
    c.execute("""CREATE TABLE stock (
                name text,
                quantity integer,
                cost integer
                ) """)
    conn.commit()
except Exception:
        print('DB exists')

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(580, 355)
        self.login = QtWidgets.QPushButton(Form)
        self.login.setGeometry(QtCore.QRect(220, 230, 113, 32))
        self.login.setObjectName("login")
        self.login.clicked.connect(self.loginfunction)

        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(70, 70, 60, 16))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(70, 120, 60, 16))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(200, 170, 200, 30))
        self.label_3.setObjectName("label_3")
        self.textEdit = QtWidgets.QTextEdit(Form)
        self.textEdit.setGeometry(QtCore.QRect(160, 70, 161, 21))
        self.textEdit.setObjectName("textEdit")
        self.textEdit_2 = QtWidgets.QTextEdit(Form)
        self.textEdit_2.setGeometry(QtCore.QRect(160, 120, 161, 21))
        self.textEdit_2.setObjectName("textEdit_2")
        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)
    
    def loginfunction(self):
        user = self.textEdit.toPlainText()
        password = self.textEdit_2.toPlainText()
        print(user)
        print(password)
        conn = sqlite3.connect("shows.db")
        cur = conn.cursor()
        cur1 = conn.cursor()

        user_info = [user, password]
        cur.execute('INSERT INTO Shows (Title, Director) VALUES (?,?)', user_info)
        cur1.execute("SELECT * FROM Shows")

        rows = cur1.fetchall()

        for row in rows:
         print(row[0])
         self.label_3.setText(row[0])

      

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.login.setText(_translate("Form", "login"))
        self.label.setText(_translate("Form", "Name"))
        self.label_2.setText(_translate("Form", "prenom"))
        self.label_3.setText(_translate("Form", "prenom"))
      
if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    
    sys.exit(app.exec_())
    